/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objects.SanPham;
import FileIOCSV.FileIOSanPham;
import FileIOCSV.FileIOHoaDon;
import QuanLy.QuanLyBanHang;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class BanHangFrame extends javax.swing.JFrame {

    FileIOHoaDon fileIOHoaDon = new FileIOHoaDon();
    FileIOSanPham fileIOSanPham = new FileIOSanPham();
    QuanLyBanHang quanLyBanHang = new QuanLyBanHang();
    List<SanPham> listSanPham;
    List<SanPham> listTable = new ArrayList<>();
    List<Integer> listMaSP = new ArrayList<>();
    DefaultTableModel model;
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    int tongTien = 0, Tong = 0, giamGia = 0;

    /**
     * Creates new form BanHangFrame
     */
    public BanHangFrame() {
        initComponents();
        model = (DefaultTableModel) SanPhamTable.getModel();
        setTimeField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TimeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TenSanPhamField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        GiaBanField = new javax.swing.JTextField();
        ThanhTienField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SanPhamTable = new javax.swing.JTable();
        TimKiemField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AddProductButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        SoLuongField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        PrintButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        GiamGiaField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TongField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TongTienField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bán Hàng");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hóa Đơn Bán Hàng");
        jLabel1.setAutoscrolls(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Thời gian");

        TimeField.setEditable(false);
        TimeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tên Sản Phẩm");

        TenSanPhamField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TenSanPhamField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TenSanPhamFieldFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Giá Bán");

        GiaBanField.setEditable(false);
        GiaBanField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ThanhTienField.setEditable(false);
        ThanhTienField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Thành Tiền");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thông tin sản phẩm");

        SanPhamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá Bán", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SanPhamTable);
        if (SanPhamTable.getColumnModel().getColumnCount() > 0) {
            SanPhamTable.getColumnModel().getColumn(0).setMinWidth(35);
            SanPhamTable.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        TimKiemField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Tìm Kiếm");

        AddProductButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddProductButton.setText("Thêm Sản Phẩm");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Số Lượng");

        SoLuongField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SoLuongField.setText("0");
        SoLuongField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SoLuongFieldFocusLost(evt);
            }
        });
        SoLuongField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SoLuongFieldKeyPressed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddButton.setText("Thêm Hóa Đơn");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        PrintButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PrintButton.setText("In Hóa Đơn");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelButton.setText("Hủy Hóa Đơn");
        CancelButton.setToolTipText("");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ExitButton.setText("Thoát");
        ExitButton.setToolTipText("");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Tổng");

        GiamGiaField.setEditable(false);
        GiamGiaField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GiamGiaField.setText("0");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Giảm Giá");

        TongField.setEditable(false);
        TongField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TongField.setText("0");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Tổng Tiền");

        TongTienField.setEditable(false);
        TongTienField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TongTienField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(AddButton)
                        .addGap(93, 93, 93)
                        .addComponent(PrintButton)
                        .addGap(99, 99, 99)
                        .addComponent(CancelButton)
                        .addGap(109, 109, 109)
                        .addComponent(ExitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(TongField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(GiamGiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(TongTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddProductButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TenSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SoLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(GiaBanField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(ThanhTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TenSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(SoLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(GiaBanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ThanhTienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(AddProductButton)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(GiamGiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(TongField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TongTienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(PrintButton)
                    .addComponent(CancelButton)
                    .addComponent(ExitButton))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        listSanPham = fileIOSanPham.SanPhamReadCSV();
        for (int j = 0; j < listSanPham.size(); j++) {
            SanPham test = listSanPham.get(j);
            if (test.getMaSanPham() == listMaSP.get(listMaSP.size() - 1)) {
                test.setSoLuong(Integer.parseInt(SoLuongField.getText()));
                listTable.add(test);
            }
        }
        if (listTable.size() >= 10) {
            giamGia = 5;
        } else if (listTable.size() >= 20) {
            giamGia = 10;
        }
        Tong += Integer.parseInt(ThanhTienField.getText());
        tongTien = (int) (Tong * (1.0 - giamGia / 100));
        updateTable();
        TongField.setText(String.valueOf(Tong));
        GiamGiaField.setText(String.valueOf(giamGia));
        TongTienField.setText(String.valueOf(tongTien));
        Reset();
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        quanLyBanHang.BanHang(listTable, TimeField.getText(), giamGia, tongTien);
        this.dispose();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        while (!listTable.isEmpty()) {
            listTable.remove(0);
        }
        i = 1;
        tongTien = 0;
        Tong = 0;
        giamGia = 0;
        TongField.setText(String.valueOf(Tong));
        GiamGiaField.setText(String.valueOf(giamGia));
        TongTienField.setText(String.valueOf(tongTien));
        Reset();
        setTimeField();
        updateTable();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void TenSanPhamFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TenSanPhamFieldFocusLost

        listSanPham = fileIOSanPham.SanPhamReadCSV();
        int j;
        if (TenSanPhamField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được để trống");
        } else {
            for (j = 0; j < listSanPham.size(); j++) {
                if (listSanPham.get(j).getTenSanPham().equals(TenSanPhamField.getText())) {
                    listMaSP.add(listSanPham.get(j).getMaSanPham());
                    GiaBanField.setText(String.valueOf(listSanPham.get(j).getGiaBan()));
                    break;
                } else if ((j + 1) == listSanPham.size()) {
                    JOptionPane.showMessageDialog(rootPane, "Nhập sai tên sản phẩm.");
                }
            }
        }
    }//GEN-LAST:event_TenSanPhamFieldFocusLost

    private void SoLuongFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SoLuongFieldFocusLost
        String s = SoLuongField.getText().trim();
        if (s.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống");
        } else {
            int soLuong = Integer.parseInt(SoLuongField.getText());
            int sum = soLuong * Integer.parseInt(GiaBanField.getText());
            ThanhTienField.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_SoLuongFieldFocusLost

    private void SoLuongFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoLuongFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoLuongFieldKeyPressed

    private void Reset() {
        TenSanPhamField.setText("");
        SoLuongField.setText("");
        GiaBanField.setText("");
        ThanhTienField.setText("");
    }

    private void setTimeField() {
        Date date = new Date();
        String time = dateFormat.format(date);
        TimeField.setText(time);
    }
 
    int i = 1;

    private void updateTable() {
        int index = listTable.size() - 1;
        if (index != -1) {
            SanPham s = listTable.get(index);
            model.addRow(new Object[]{i, s.getMaSanPham(), s.getTenSanPham(), s.getSoLuong(), s.getGiaBan(), ThanhTienField.getText()});
            i++;
        } else {
            model.setRowCount(0);
        }
    }

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BanHangFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddProductButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField GiaBanField;
    private javax.swing.JTextField GiamGiaField;
    private javax.swing.JButton PrintButton;
    private javax.swing.JTable SanPhamTable;
    private javax.swing.JTextField SoLuongField;
    private javax.swing.JTextField TenSanPhamField;
    private javax.swing.JTextField ThanhTienField;
    private javax.swing.JTextField TimKiemField;
    private javax.swing.JTextField TimeField;
    private javax.swing.JTextField TongField;
    private javax.swing.JTextField TongTienField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
