/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objects.HoaDonBanHang;
import Objects.HoaDonNhapHang;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import FileIOCSV.FileIOHoaDon;

/**
 *
 * @author admin
 */
public class HoaDonFrame extends javax.swing.JFrame {
    
    List<HoaDonBanHang> listHDBH = new ArrayList<>();
    List<HoaDonNhapHang> listHDNH = new ArrayList<>();
    DefaultTableModel BanHangModel;
    DefaultTableModel NhapHangModel;
    FileIOHoaDon f = new FileIOHoaDon();

    /**
     * Creates new form HoaDonFrame
     */
    public HoaDonFrame() {
        initComponents();
        listHDBH = f.BanHangReadCSV(f.FileHoaDonBanHang);
        listHDNH = f.NhapHangReadCSV(f.FileHoaDonNhapHang);
        BanHangModel = (DefaultTableModel) BanHangTable.getModel();
        NhapHangModel = (DefaultTableModel) NhapHangTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        HoaDonBanHang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BanHangTable = new javax.swing.JTable();
        PrintButton1 = new javax.swing.JButton();
        EditButton1 = new javax.swing.JButton();
        DeleteButton1 = new javax.swing.JButton();
        ExitButton1 = new javax.swing.JButton();
        SaveButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FindField1 = new javax.swing.JTextField();
        HoaDonNhapHang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NhapHangTable = new javax.swing.JTable();
        PrintButton2 = new javax.swing.JButton();
        EditButton2 = new javax.swing.JButton();
        DeleteButton2 = new javax.swing.JButton();
        SaveButton2 = new javax.swing.JButton();
        ExitButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FindField2 = new javax.swing.JTextField();

        setTitle("Hóa Đơn");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hóa Đơn Bán Hàng");

        BanHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Ngày Lập", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Giảm Giá", "Thành Tiền"
            }
        ));
        jScrollPane1.setViewportView(BanHangTable);
        if (BanHangTable.getColumnModel().getColumnCount() > 0) {
            BanHangTable.getColumnModel().getColumn(0).setMinWidth(35);
            BanHangTable.getColumnModel().getColumn(0).setMaxWidth(35);
            BanHangTable.getColumnModel().getColumn(1).setMinWidth(80);
            BanHangTable.getColumnModel().getColumn(3).setMinWidth(80);
            BanHangTable.getColumnModel().getColumn(4).setMinWidth(150);
            BanHangTable.getColumnModel().getColumn(5).setMinWidth(80);
            BanHangTable.getColumnModel().getColumn(7).setMinWidth(50);
            BanHangTable.getColumnModel().getColumn(7).setMaxWidth(80);
        }

        PrintButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PrintButton1.setText("In Hóa Đơn");
        PrintButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButton1ActionPerformed(evt);
            }
        });

        EditButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EditButton1.setText("Sửa Hóa Đơn");
        EditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton1ActionPerformed(evt);
            }
        });

        DeleteButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DeleteButton1.setText("Xóa Hóa Đơn");
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });

        ExitButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ExitButton1.setText("Thoát");
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });

        SaveButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SaveButton1.setText("Lưu");
        SaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        FindField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout HoaDonBanHangLayout = new javax.swing.GroupLayout(HoaDonBanHang);
        HoaDonBanHang.setLayout(HoaDonBanHangLayout);
        HoaDonBanHangLayout.setHorizontalGroup(
            HoaDonBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
            .addGroup(HoaDonBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(HoaDonBanHangLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(PrintButton1)
                .addGap(85, 85, 85)
                .addComponent(EditButton1)
                .addGap(82, 82, 82)
                .addComponent(DeleteButton1)
                .addGap(89, 89, 89)
                .addComponent(SaveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(HoaDonBanHangLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(FindField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HoaDonBanHangLayout.setVerticalGroup(
            HoaDonBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(HoaDonBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FindField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(HoaDonBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditButton1)
                        .addComponent(PrintButton1)
                        .addComponent(DeleteButton1))
                    .addGroup(HoaDonBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaveButton1)
                        .addComponent(ExitButton1)))
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Danh Sách Hóa Đơn Bán Hàng", HoaDonBanHang);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hóa Đơn Nhập Hàng");

        NhapHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Ngày Lập", "Nhà Phân Phối", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(NhapHangTable);
        if (NhapHangTable.getColumnModel().getColumnCount() > 0) {
            NhapHangTable.getColumnModel().getColumn(0).setMinWidth(35);
            NhapHangTable.getColumnModel().getColumn(0).setMaxWidth(35);
            NhapHangTable.getColumnModel().getColumn(1).setMinWidth(80);
            NhapHangTable.getColumnModel().getColumn(3).setMinWidth(150);
            NhapHangTable.getColumnModel().getColumn(4).setMinWidth(80);
            NhapHangTable.getColumnModel().getColumn(5).setMinWidth(150);
            NhapHangTable.getColumnModel().getColumn(6).setMinWidth(80);
        }

        PrintButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PrintButton2.setText("In Hóa Đơn");
        PrintButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButton2ActionPerformed(evt);
            }
        });

        EditButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EditButton2.setText("Sửa Hóa Đơn");
        EditButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton2ActionPerformed(evt);
            }
        });

        DeleteButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DeleteButton2.setText("Xóa Hóa Đơn");
        DeleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton2ActionPerformed(evt);
            }
        });

        SaveButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SaveButton2.setText("Lưu");
        SaveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton2ActionPerformed(evt);
            }
        });

        ExitButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ExitButton2.setText("Thoát");
        ExitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tìm Kiếm");

        FindField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout HoaDonNhapHangLayout = new javax.swing.GroupLayout(HoaDonNhapHang);
        HoaDonNhapHang.setLayout(HoaDonNhapHangLayout);
        HoaDonNhapHangLayout.setHorizontalGroup(
            HoaDonNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
            .addGroup(HoaDonNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(HoaDonNhapHangLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(PrintButton2)
                .addGap(85, 85, 85)
                .addComponent(EditButton2)
                .addGap(82, 82, 82)
                .addComponent(DeleteButton2)
                .addGap(89, 89, 89)
                .addComponent(SaveButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(HoaDonNhapHangLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(FindField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HoaDonNhapHangLayout.setVerticalGroup(
            HoaDonNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(HoaDonNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FindField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(HoaDonNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditButton2)
                        .addComponent(PrintButton2)
                        .addComponent(DeleteButton2))
                    .addGroup(HoaDonNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaveButton2)
                        .addComponent(ExitButton2)))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Danh Sách Hóa Đơn Nhập Hàng", HoaDonNhapHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButton1ActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButton1ActionPerformed

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void EditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButton1ActionPerformed

    private void PrintButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButton1ActionPerformed

    private void PrintButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButton2ActionPerformed

    private void EditButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButton2ActionPerformed

    private void DeleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButton2ActionPerformed

    private void SaveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButton2ActionPerformed

    private void ExitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButton2ActionPerformed
    
    public void showResult(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BanHangTable;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton DeleteButton2;
    private javax.swing.JButton EditButton1;
    private javax.swing.JButton EditButton2;
    private javax.swing.JButton ExitButton1;
    private javax.swing.JButton ExitButton2;
    private javax.swing.JTextField FindField1;
    private javax.swing.JTextField FindField2;
    private javax.swing.JPanel HoaDonBanHang;
    private javax.swing.JPanel HoaDonNhapHang;
    private javax.swing.JTable NhapHangTable;
    private javax.swing.JButton PrintButton1;
    private javax.swing.JButton PrintButton2;
    private javax.swing.JButton SaveButton1;
    private javax.swing.JButton SaveButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
