/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objects.SanPham;
import FileIOCSV.FileIOHoaDon;
import FileIOCSV.FileIOSanPham;
import QuanLy.QuanLyBanHang;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class NhapHangFrame extends javax.swing.JFrame {

    FileIOSanPham fileIOSanPham = new FileIOSanPham();
    FileIOHoaDon fileIOHoaDon = new FileIOHoaDon();
    QuanLyBanHang quanLyBanHang = new QuanLyBanHang();
    public List<SanPham> listSanPhamNhap = new ArrayList<>();
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DefaultTableModel TableModel;

    int thanhTien = 0, Tong = 0;

    /**
     * Creates new form NhapHangFrame
     */
    public NhapHangFrame() {
        initComponents();
        TableModel = (DefaultTableModel) SanPhamNhapTable.getModel();
        setTimeField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TimeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        NhaSXField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        QuantityField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ThanhTienField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LoaiSPField = new javax.swing.JTextField();
        MFDField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EXPField = new javax.swing.JTextField();
        DonViTinhField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SanPhamNhapTable = new javax.swing.JTable();
        AddProductButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        PrintButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        SumOfAllField = new javax.swing.JTextField();
        ResetButton = new javax.swing.JButton();
        EditProductButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập Hàng");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hóa Đơn Nhập Hàng");
        jLabel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Mã Hóa Đơn");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Thời Gian");

        TimeField.setEditable(false);
        TimeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thông Tin Sản Phẩm");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tên Sản Phẩm");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Nhà Sản Xuất");

        NameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });

        NhaSXField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NhaSXField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NhaSXFieldFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Số Lượng");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Đơn Vị Tính");

        QuantityField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        QuantityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                QuantityFieldFocusLost(evt);
            }
        });

        PriceField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PriceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PriceFieldFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Giá Nhập");

        ThanhTienField.setEditable(false);
        ThanhTienField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ThanhTienField.setText("0");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Loại Sản Phẩm");

        LoaiSPField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        MFDField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MFDField.setText("01/01/2000");
        MFDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MFDFieldFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Thành Tiền");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Ngày Sản Xuất");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Hạn Sử Dụng");

        EXPField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EXPField.setText("01/01/2000");
        EXPField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EXPFieldFocusLost(evt);
            }
        });

        DonViTinhField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        SanPhamNhapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Sản Phẩm", "Loại Sản Phẩm", "Số Lượng", "Giá Nhập", "Đơn Vị Tính", "NSX", "HSD", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SanPhamNhapTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanPhamNhapTableMouseClicked(evt);
            }
        });
        SanPhamNhapTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SanPhamNhapTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(SanPhamNhapTable);
        if (SanPhamNhapTable.getColumnModel().getColumnCount() > 0) {
            SanPhamNhapTable.getColumnModel().getColumn(0).setMinWidth(50);
            SanPhamNhapTable.getColumnModel().getColumn(0).setMaxWidth(50);
            SanPhamNhapTable.getColumnModel().getColumn(3).setMinWidth(80);
            SanPhamNhapTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        AddProductButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddProductButton.setText("Thêm Sản Phẩm");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddButton.setText("Thêm Hóa Đơn");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        PrintButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PrintButton.setText("In Hóa Đơn");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelButton.setText("Hủy Hóa Đơn");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ExitButton.setText("Thoát");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Tổng");

        SumOfAllField.setEditable(false);
        SumOfAllField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ResetButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        EditProductButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EditProductButton.setText("Sửa Sản Phẩm");
        EditProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(26, 26, 26)
                                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel9))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DonViTinhField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(LoaiSPField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(49, 49, 49)
                                                .addComponent(ThanhTienField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                                        .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(122, 122, 122)
                                                    .addComponent(AddProductButton)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(193, 193, 193)
                                        .addComponent(EditProductButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EXPField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MFDField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ResetButton))))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(403, 403, 403)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SumOfAllField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(AddButton)
                                .addGap(109, 109, 109)
                                .addComponent(PrintButton)
                                .addGap(132, 132, 132)
                                .addComponent(CancelButton)
                                .addGap(143, 143, 143)
                                .addComponent(ExitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(NhaSXField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(NhaSXField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(LoaiSPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(MFDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(EXPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ThanhTienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DonViTinhField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditProductButton)
                    .addComponent(AddProductButton)
                    .addComponent(ResetButton))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumOfAllField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(CancelButton)
                    .addComponent(ExitButton)
                    .addComponent(PrintButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed

    }//GEN-LAST:event_PrintButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        quanLyBanHang.NhapHang(listSanPhamNhap, TimeField.getText(), Tong);
        this.dispose();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        while (!listSanPhamNhap.isEmpty()) {
            listSanPhamNhap.remove(0);
        }
        i = 1;
        thanhTien = 0;
        Tong = 0;
        Reset();
        setTimeField();
        updateTable();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        SanPham s = new SanPham();
        s.setTenSanPham(NameField.getText());
        s.setNhaSX(NhaSXField.getText());
        s.setLoaiSanPham(LoaiSPField.getText());
        s.setSoLuong(Integer.parseInt(QuantityField.getText()));
        s.setDonViTinh(DonViTinhField.getText());
        s.setGiaNhap(Integer.parseInt(PriceField.getText()));
        s.setGiaBan();
        LocalDate NSX = LocalDate.parse(MFDField.getText(), dateTimeFormatter);
        LocalDate HSD = LocalDate.parse(EXPField.getText(), dateTimeFormatter);
        s.setNSX(NSX);
        s.setHSD(HSD);
        listSanPhamNhap.add(s);
        Tong += s.getGiaNhap() * s.getSoLuong();
        SumOfAllField.setText(String.valueOf(Tong));
        updateTable();
        Reset();
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void SanPhamNhapTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamNhapTableMouseClicked
        int selectedIndex = SanPhamNhapTable.getSelectedRow();

        displayDetails(selectedIndex);
    }//GEN-LAST:event_SanPhamNhapTableMouseClicked

    private void SanPhamNhapTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SanPhamNhapTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int selectedIndex = SanPhamNhapTable.getSelectedRow();
            displayDetails(selectedIndex);
        }
    }//GEN-LAST:event_SanPhamNhapTableKeyReleased

    private void EditProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductButtonActionPerformed
        int selectedIndex = SanPhamNhapTable.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn sản phẩm cần sửa!");
        } else {
            int result = JOptionPane.showConfirmDialog(rootPane,
                    "Bạn có chắc muốn sửa sản phẩm này?",
                    "Xác Nhận",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {
                SanPham s = listSanPhamNhap.get(selectedIndex);
                s.setTenSanPham(NameField.getText());
                s.setNhaSX(NhaSXField.getText());
                s.setLoaiSanPham(LoaiSPField.getText());
                s.setSoLuong(Integer.parseInt(QuantityField.getText()));
                s.setDonViTinh(DonViTinhField.getText());
                s.setGiaNhap(Integer.parseInt(PriceField.getText()));
                s.setGiaBan();
                LocalDate NSX = LocalDate.parse(MFDField.getText(), dateTimeFormatter);
                LocalDate HSD = LocalDate.parse(EXPField.getText(), dateTimeFormatter);
                s.setNSX(NSX);
                s.setHSD(HSD);
                listSanPhamNhap.set(selectedIndex, s);
                updateTable();
                Reset();
            }
        }
    }//GEN-LAST:event_EditProductButtonActionPerformed

    private void NhaSXFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NhaSXFieldFocusLost
        if (NhaSXField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nhà sản xuất không được để trống!");
        }
    }//GEN-LAST:event_NhaSXFieldFocusLost

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        if (NameField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tên không được để trống!");
        }
    }//GEN-LAST:event_NameFieldFocusLost

    private void QuantityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QuantityFieldFocusLost
        if (QuantityField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng không được để trống!");
        } else {
            boolean ok = true;
            try {
                int soLuong = Integer.parseInt(QuantityField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số Lượng không được chứa kí tự khác!");
                ok = false;
            }
            if (ok) {
                int soLuong = Integer.parseInt(QuantityField.getText());
                if (soLuong <= 0) {
                    JOptionPane.showMessageDialog(rootPane, "Số lượng phải lớn hơn 0!");
                } else if (!PriceField.getText().trim().equals("")) {
                    int giaNhap = Integer.parseInt(PriceField.getText());
                    ThanhTienField.setText(String.valueOf(giaNhap * soLuong));
                }
            }
        }
    }//GEN-LAST:event_QuantityFieldFocusLost

    private void PriceFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PriceFieldFocusLost
        if (PriceField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Giá nhập không được để trống!");
        } else {
            boolean ok = true;
            try {
                int giaNhap = Integer.parseInt(PriceField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Giá nhập không được chứa kí tự khác!");
                ok = false;
            }
            if (ok) {
                int giaNhap = Integer.parseInt(PriceField.getText());
                if (giaNhap <= 0) {
                    JOptionPane.showMessageDialog(rootPane, "Giá nhập phải lớn hơn 0!");
                } else if (!QuantityField.getText().trim().equals("")) {
                    int soLuong = Integer.parseInt(QuantityField.getText());
                    ThanhTienField.setText(String.valueOf(giaNhap * soLuong));
                }
            }
        }
    }//GEN-LAST:event_PriceFieldFocusLost

    private void MFDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MFDFieldFocusLost
        String reg = "^\\d{2}/\\d{2}/\\d{4}$";
        if (!MFDField.getText().matches(reg)) {
            JOptionPane.showMessageDialog(rootPane, "NSX sai định dạng!");
        } else {
            String[] s = MFDField.getText().split("/");
            int d = Integer.parseInt(s[0]);
            int m = Integer.parseInt(s[1]);
            int y = Integer.parseInt(s[2]);
            if (m == 0 || m > 12) {
                JOptionPane.showMessageDialog(rootPane, "Tháng không hợp lệ!");
            } else {
                if (d <= 0) {
                    JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                } else {
                    switch (m) {
                        case 1:
                        case 3:
                        case 5:
                        case 7:
                        case 8:
                        case 10:
                        case 12:
                            if (d > 31) {
                                JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                            }
                            break;
                        case 4:
                        case 6:
                        case 9:
                        case 11:
                            if (d > 30) {
                                JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                            }
                            break;
                        case 2:
                            if ((y % 4 == 0 && y % 100 != 0) || y % 400 == 0) {
                                if (d > 29) {
                                    JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                                }
                            } else {
                                if (d > 28) {
                                    JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                                }
                            }
                            break;
                        default:
                            JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                    }
                }
            }
        }
    }//GEN-LAST:event_MFDFieldFocusLost

    private void EXPFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EXPFieldFocusLost
        String reg = "^\\d{2}/\\d{2}/\\d{4}$";
        if (!EXPField.getText().matches(reg)) {
            JOptionPane.showMessageDialog(rootPane, "HSD sai định dạng!");
        } else {
            String[] s = EXPField.getText().split("/");
            int d = Integer.parseInt(s[0]);
            int m = Integer.parseInt(s[1]);
            int y = Integer.parseInt(s[2]);
            if (m == 0 || m > 12) {
                JOptionPane.showMessageDialog(rootPane, "Tháng không hợp lệ!");
            } else {
                if (d <= 0) {
                    JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                } else {
                    switch (m) {
                        case 1:
                        case 3:
                        case 5:
                        case 7:
                        case 8:
                        case 10:
                        case 12:
                            if (d > 31) {
                                JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                            }
                            break;
                        case 4:
                        case 6:
                        case 9:
                        case 11:
                            if (d > 30) {
                                JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                            }
                            break;
                        case 2:
                            if ((y % 4 == 0 && y % 100 != 0) || y % 400 == 0) {
                                if (d > 29) {
                                    JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                                }
                            } else {
                                if (d > 28) {
                                    JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                                }
                            }
                            break;
                        default:
                            JOptionPane.showMessageDialog(rootPane, "Ngày không hợp lệ!");
                    }
                }
            }
        }
    }//GEN-LAST:event_EXPFieldFocusLost

    private void Reset() {
        NameField.setText("");
        LoaiSPField.setText("");
        QuantityField.setText("");
        DonViTinhField.setText("");
        PriceField.setText("");
        MFDField.setText("01/01/2000");
        EXPField.setText("01/01/2000");
        ThanhTienField.setText("");
    }

    private void setTimeField() {
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String time = dateFormat.format(date);
        TimeField.setText(time);
    }

    private void displayDetails(int selectedIndex) {
        SanPham s = listSanPhamNhap.get(selectedIndex);

        NameField.setText(s.getTenSanPham());
        NhaSXField.setText(s.getNhaSX());
        LoaiSPField.setText(s.getLoaiSanPham());
        QuantityField.setText(String.valueOf(s.getSoLuong()));
        DonViTinhField.setText(s.getDonViTinh());
        PriceField.setText(String.valueOf(s.getGiaNhap()));
        MFDField.setText(s.getNSX().format(dateTimeFormatter));
        EXPField.setText(s.getHSD().format(dateTimeFormatter));
    }

    int i = 1;

    public void updateTable() {
        TableModel.setRowCount(0);
        for (SanPham s : listSanPhamNhap) {
            TableModel.addRow(new Object[]{i, s.getTenSanPham(), s.getLoaiSanPham(), s.getSoLuong(), s.getGiaNhap(), s.getDonViTinh(), s.getNSX(), s.getHSD(), (s.getSoLuong() * s.getGiaNhap())});
            i++;
            SanPhamNhapTable.scrollRectToVisible(SanPhamNhapTable.getCellRect(SanPhamNhapTable.getRowCount() - 1, 0, true));
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NhapHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NhapHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NhapHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NhapHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NhapHangFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddProductButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DonViTinhField;
    private javax.swing.JTextField EXPField;
    private javax.swing.JButton EditProductButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField LoaiSPField;
    private javax.swing.JTextField MFDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField NhaSXField;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton PrintButton;
    private javax.swing.JTextField QuantityField;
    private javax.swing.JButton ResetButton;
    private javax.swing.JTable SanPhamNhapTable;
    private javax.swing.JTextField SumOfAllField;
    private javax.swing.JTextField ThanhTienField;
    private javax.swing.JTextField TimeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
